apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-engine
  namespace: yarnmarket-prod
  labels:
    app: conversation-engine
    version: v1.0.0
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  selector:
    matchLabels:
      app: conversation-engine
  template:
    metadata:
      labels:
        app: conversation-engine
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: conversation-engine
        image: yarnmarket/conversation-engine:latest
        ports:
        - containerPort: 8001
          name: http
        - containerPort: 8090
          name: metrics
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: postgres-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: redis-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mongodb-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai-api-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
          readOnly: true
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      imagePullSecrets:
      - name: docker-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: conversation-engine-service
  namespace: yarnmarket-prod
  labels:
    app: conversation-engine
spec:
  selector:
    app: conversation-engine
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  - name: metrics
    port: 8090
    targetPort: 8090
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conversation-engine-hpa
  namespace: yarnmarket-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversation-engine
  minReplicas: 5
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: active_conversations
      target:
        type: AverageValue
        averageValue: "100"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: conversation-engine-pdb
  namespace: yarnmarket-prod
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: conversation-engine